Fix pace script formatting and input

diff --git a/scripts/vimj b/scripts/vimj
--- a/scripts/vimj
+++ b/scripts/vimj
@@ -3,8 +3,8 @@
 JOURNAL="$HOME/.journal"
 
 if [ ! -e "$JOURNAL" ]; then
-    echo "Error: $JOURNAL does not exist" >&2
-    exit 1
+	echo "Error: $JOURNAL does not exist" >&2
+	exit 1
 fi
 
-vim "$JOURNAL"
+nvim "$JOURNAL"
